In [ ]:
import numpy as np
n = np.array([1,2,3,4])
print(n)
print(type(n))


[1 2 3 4]
<class 'numpy.ndarray'>
1


In [23]:
n2 = np.array([[1,2,3,], [4,5,6]])
print(n2)
print(type(n2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [21]:
n3 = np.array([[[1,2], [5,6], [7,8]]])
print(n3)
print(type(n3))

[[[1 2]
  [5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [22]:
print(n.shape,n2.shape, n3.shape)
print(n.ndim, n2.ndim,n3.ndim)
print(n.size, n2.size)


(4,) (2, 3) (1, 3, 2)
1 2 3
4 6


## Numpy Maths

In [5]:
import numpy as np
a = np.array([1,2,3,4])
z = np.zeros((5,10))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
one = np.ones([5,5], dtype=int)
one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
n = np.eye((5), dtype=int)
n

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
o = np.random.random((3,4))
o

array([[0.70847039, 0.44992296, 0.56155277, 0.28862535],
       [0.13595959, 0.57593471, 0.86135778, 0.87619393],
       [0.08270213, 0.8358539 , 0.2983784 , 0.89386398]])

In [ ]:
k = np.random.randint(1,11,(5,5))  # start, stop, shape
k

array([[ 8,  4, 10,  3,  7],
       [ 8,  6,  5, 10,  4],
       [10,  5,  5,  3,  8],
       [ 9,  7,  9,  7, 10],
       [10,  8,  3,  5,  2]], dtype=int32)

In [28]:
a = np.array([1,2,3])
b = np.array([3,4,5])
c = a + b
d = a-b
e = a/b
f = a*b
print(c,d,e,f, sep="\n")

[4 6 8]
[-2 -2 -2]
[0.33333333 0.5        0.6       ]
[ 3  8 15]


In [29]:
print(np.sin(a))
print(np.cos(b))
print(np.cos(c))

[0.84147098 0.90929743 0.14112001]
[-0.9899925  -0.65364362  0.28366219]
[-0.65364362  0.96017029 -0.14550003]


## Maths & Stats

In [ ]:
x = np.array([[2,4],[5,11],[3,4]])
print(x.mean())
print(x.mean(axis=0))
print(x.mean(axis=1))


4.833333333333333
[3.33333333 6.33333333]
[3.  8.  3.5]


In [41]:
print(x.sum(axis=1))
print(x.max(axis=1))
print(x.min(axis=1))

[ 6 16  7]
[ 4 11  4]
[2 5 3]


## props

In [45]:
print(x.ndim)
print(x.shape)
print(x.size)

2
(3, 2)
6
