In [ ]:
import numpy as np
n = np.array([1,2,3,4])
print(n)
print(type(n))


[1 2 3 4]
<class 'numpy.ndarray'>
1


In [23]:
n2 = np.array([[1,2,3,], [4,5,6]])
print(n2)
print(type(n2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [21]:
n3 = np.array([[[1,2], [5,6], [7,8]]])
print(n3)
print(type(n3))

[[[1 2]
  [5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [22]:
print(n.shape,n2.shape, n3.shape)
print(n.ndim, n2.ndim,n3.ndim)
print(n.size, n2.size)


(4,) (2, 3) (1, 3, 2)
1 2 3
4 6
